tercdev/Clear_Lake_Website_Data_Visualization

Data Visualization Code/Stream/streamScript.js

Clean Stream data

---

clear-lake-restoration-app/package-lock.json
clear-lake-restoration-app/package.json
clear-lake-restoration-app/src/App.css
clear-lake-restoration-app/src/App.js
clear-lake-restoration-app/src/Components/Map.js
clear-lake-restoration-app/src/Components/Navbar.js
clear-lake-restoration-app/src/Components/StreamMap.js
clear-lake-restoration-app/src/Components/pages/Home.js
clear-lake-restoration-app/src/Components/pages/lake/Lake.js
clear-lake-restoration-app/src/Components/pages/met/Met.js
clear-lake-restoration-app/src/Components/pages/streams/Kelsey.js
clear-lake-restoration-app/src/Components/pages/streams/Stream.js
clear-lake-restoration-app/src/index.js

maps with locations of stream monitoring sites, met stations, lake moorings

---

clear-lake-restoration-app/package-lock.json
clear-lake-restoration-app/package.json
clear-lake-restoration-app/src/App.css
clear-lake-restoration-app/src/App.js
clear-lake-restoration-app/src/Components/DateRangePicker.css
clear-lake-restoration-app/src/Components/DateRangePicker.js
clear-lake-restoration-app/src/Components/StreamChart.js
clear-lake-restoration-app/src/Components/pages/streams/Stream.js
clear-lake-restoration-app/src/Components/pages/streams/StreamHome.js
clear-lake-restoration-app/src/hooks/useFetch.js

This PR integrates highcharts data vis [Turb and Temp] for streams.

integrating stream charts

---

clear-lake-restoration-app/package-lock.json
clear-lake-restoration-app/package.json
clear-lake-restoration-app/src/App.css
clear-lake-restoration-app/src/App.js
clear-lake-restoration-app/src/Components/Map.js

add legend and popups to map

---

clear-lake-restoration-app/package-lock.json
clear-lake-restoration-app/package.json
clear-lake-restoration-app/src/App.js
clear-lake-restoration-app/src/Components/Map.js

Can be found at https://tercdev.github.io/Clear_Lake_Website_Data_Visualization/
npm run deploy on the branch you want to be on the site (and it will automatically update gh-pages branch)

Host React GitHub pages

---

clear-lake-restoration-app/src/App.js
clear-lake-restoration-app/src/Components/LakeChart.js
clear-lake-restoration-app/src/Components/StreamChart.js
clear-lake-restoration-app/src/Components/pages/lake/Lake.js

In this PR I added some lake charts for our lake pages. Date picker is not working yet and some charts are missing

Added lake charts

---

clear-lake-restoration-app/package-lock.json
clear-lake-restoration-app/src/Components/StreamChart.js
clear-lake-restoration-app/src/Components/pages/met/Met.js
clear-lake-restoration-app/src/Components/pages/streams/Stream.js

added flow chart and fixed time issue

---

clear-lake-restoration-app/src/App.css
clear-lake-restoration-app/src/Components/pages/streams/Stream.css

specifically the data disclaimer and date picker

fix mobile view format of stream pages

---

Data Visualization Code/Meteorology/metScript.js
Data Visualization Code/Stream/streamScript.js

this PR added flow chart to the site farm data vis using the APIs

added flow chart into sitefarm data vis

---

clear-lake-restoration-app/package-lock.json
clear-lake-restoration-app/package.json
clear-lake-restoration-app/src/App.css
clear-lake-restoration-app/src/Components/Map.css
clear-lake-restoration-app/src/Components/Map.js

- hover over marker for popup
- click on marker redirects to page w graphs
- different legend
- refactored some functions

map changes

---

clear-lake-restoration-app/src/Components/Map.js

small map changes

---

clear-lake-restoration-app/src/Components/Navigation.js

- could not figure out a different way to format

add wind and sitefarm tabs

---

clear-lake-restoration-app/src/Components/MeterologyData.js
clear-lake-restoration-app/src/Components/StreamData.js

data archive with variable selection

---

clear-lake-restoration-app/package-lock.json
clear-lake-restoration-app/package.json
clear-lake-restoration-app/src/App.js

merge this branch if there's problems with building and deploying

code splitting w suspense and lazy

---

clear-lake-restoration-app/package.json
clear-lake-restoration-app/src/App.js

Reverts tercdev/Clear_Lake_Website_Data_Visualization#50

Revert "code splitting w suspense and lazy"

---

clear-lake-restoration-app/src/Components/pages/met/Met.js
clear-lake-restoration-app/src/Components/pages/met/MetChart.js
clear-lake-restoration-app/src/Components/utils.js

This PR refactors Met Chart components so fetching of data is done simultaneously for all met charts. 
I also added loading visual on charts.

refactored met chart components

---

clear-lake-restoration-app/src/Components/pages/met/Met.js

met graphs styling

---

clear-lake-restoration-app/src/Components/pages/lakeCTD/LakeCTD.css
clear-lake-restoration-app/src/Components/pages/lakeCTD/LakeCTD.js
clear-lake-restoration-app/src/Components/pages/lakeCTD/SpecificDateSelect.js

- date labels
- add text
- reduce width of chart

update ctd graph page

---

clear-lake-restoration-app/src/Components/pages/lakeCTD/LakeCTD.js

- fixed y ranges to compare between sites
- easy to completely remove fixed y range if not wanted
Questions probably for Alicia/Micah
- turbidity 0-150?
- should y values below 0 not be plotted?

checked y range for all sites

---

clear-lake-restoration-app/src/App.css
clear-lake-restoration-app/src/Components/Navigation.css

Made the navbar look more close to the sitefarm navbar. Sharp edges, no padding between options.

Styling changes to Navbar

---

clear-lake-restoration-app/src/Components/DateRangePicker.js
clear-lake-restoration-app/src/Components/pages/lakeTChain/LakeTchain.js
clear-lake-restoration-app/src/Components/pages/streams/Stream.js

* Adds ability to fetch multiple years for Stream charts and Lake Moorings charts
* Made Lake Moorings fetch a year back on load
* fixed timezone issues

Csayuso multipleyears

---

clear-lake-restoration-app/src/Components/Map.js
clear-lake-restoration-app/src/Components/Navigation.js
clear-lake-restoration-app/src/Components/pages/lakeCTD/LakeCTDHome.js

to solve
now no longer hoverable

map pop ups

---

clear-lake-restoration-app/src/Components/pages/lakeTChain/LakeTchain.js
clear-lake-restoration-app/src/Components/pages/lakeTChain/LakeTchainHome.js

Fixed the problem where the color axis labels sometimes ended up in the middle of the graph. Made the color axis and corresponding label a little more responsive. Fixed the problem where the color axis over lapped with the subtitle on mobile.

fix tchain graphs

---

clear-lake-restoration-app/src/Components/CollapsibleItem.js
clear-lake-restoration-app/src/Components/Map.js
clear-lake-restoration-app/src/Components/Navigation.js
clear-lake-restoration-app/src/Components/SpecificDateSelect.js
clear-lake-restoration-app/src/Components/WeatherWidget.js
clear-lake-restoration-app/src/Components/pages/data-archive/CTDData.js
clear-lake-restoration-app/src/Components/pages/data-archive/DataArchive.css
clear-lake-restoration-app/src/Components/pages/data-archive/DataArchive.js
clear-lake-restoration-app/src/Components/pages/data-archive/MeteorologyData.js
clear-lake-restoration-app/src/Components/pages/data-archive/StreamData.js
clear-lake-restoration-app/src/Components/pages/data-archive/TChainData.js
clear-lake-restoration-app/src/Components/pages/lakeCTD/LakeCTD.js
clear-lake-restoration-app/src/Components/pages/lakeTChain/LakeTchain.js
clear-lake-restoration-app/src/Components/pages/lakeTChain/LakeTchainHome.js
clear-lake-restoration-app/src/Components/pages/met/Met.js
clear-lake-restoration-app/src/Components/pages/streams/Stream.js
clear-lake-restoration-app/src/Components/pages/upload-csv/LoginForm.js
clear-lake-restoration-app/src/Components/pages/upload-csv/LoginPage.js
clear-lake-restoration-app/src/Components/pages/upload-csv/Uploader.js
clear-lake-restoration-app/src/Components/utils.js
clear-lake-restoration-app/src/hooks/useFetch.js

all files for the react app have some sort of comment

another round of comments

---

clear-lake-restoration-app/src/Components/Chart.js
clear-lake-restoration-app/src/Components/CollapsibleItem.js
clear-lake-restoration-app/src/Components/Map.js
clear-lake-restoration-app/src/Components/Navigation.js
clear-lake-restoration-app/src/Components/SpecificDateSelect.js
clear-lake-restoration-app/src/Components/WeatherWidget.js
clear-lake-restoration-app/src/Components/pages/data-archive/CTDData.js
clear-lake-restoration-app/src/Components/pages/data-archive/DataArchive.css
clear-lake-restoration-app/src/Components/pages/data-archive/DataArchive.js
clear-lake-restoration-app/src/Components/pages/data-archive/MeteorologyData.js
clear-lake-restoration-app/src/Components/pages/data-archive/StreamData.js
clear-lake-restoration-app/src/Components/pages/data-archive/TChainData.js
clear-lake-restoration-app/src/Components/pages/lakeCTD/LakeCTD.css
clear-lake-restoration-app/src/Components/pages/lakeCTD/LakeCTD.js
clear-lake-restoration-app/src/Components/pages/lakeTChain/LakeTchain.js
clear-lake-restoration-app/src/Components/pages/lakeTChain/LakeTchainHome.js
clear-lake-restoration-app/src/Components/pages/met/Met.js
clear-lake-restoration-app/src/Components/pages/streams/Stream.js
clear-lake-restoration-app/src/Components/pages/upload-csv/LoginForm.js
clear-lake-restoration-app/src/Components/pages/upload-csv/LoginPage.js
clear-lake-restoration-app/src/Components/pages/upload-csv/Uploader.js
clear-lake-restoration-app/src/Components/utils.js
clear-lake-restoration-app/src/hooks/useFetch.js

This PR fixes browser compatibility with FireFox, Safari, IE. 
To test, run this on one of those browsers.

broswer compatibility

---

clear-lake-restoration-app/src/App.js
clear-lake-restoration-app/src/Components/pages/data-archive/MeteorologyData.js
clear-lake-restoration-app/src/Components/pages/met/Met.js
clear-lake-restoration-app/src/Metadata/MetAPI.json

Added a met api file that will change id for api on all requests

Change Beakbane island id, add json file with met api info

---

clear-lake-restoration-app/src/App.js
clear-lake-restoration-app/src/Components/pages/data-archive/CTDData.js
clear-lake-restoration-app/src/Components/pages/data-archive/DataArchive.js
clear-lake-restoration-app/src/Components/pages/data-archive/TChainData.js
clear-lake-restoration-app/src/Components/pages/lakeCTD/LakeCTD.js
clear-lake-restoration-app/src/Components/pages/lakeTChain/LakeTchain.js
clear-lake-restoration-app/src/Components/pages/met/Met.js
clear-lake-restoration-app/src/Components/pages/streams/Stream.js

Havent changed stream flow and rain endpoints since the refactoring is not done and the stream pages wont work

Changed to TERC endpoints and removed upload csv page
